### ISSUE TITLE
无状态的Restful 接口 不应该使用session吧？

### ISSUE THREAD

**Issue by rushairer** [venomousboy/yii2-rest-api-captcha#1]
无状态的Restful 接口 不应该使用session吧？

**Comment by venomousboy** [comment]
That's right, restful doesn't use session. I will create a .txt file and store captcha code in it, ok?

**Comment by venomousboy** [comment]
Change captcha code storage from session to cache

https://github.com/venomousboy/yii2-rest-api-captcha/commit/1aec01db69c6482add4b03f9b807fd22d2c6c907
